const WS_STATES = {
    CONNECTING : 0,
    OPEN       : 1,
    CLOSING    : 2,
    CLOSED     : 3
};

const DEFAULT_WS_OPENING_TIMEOUT_MS = 3000;
const DEFAULT_PING_INTERVAL_MS = 10000;

module.exports = {
    WS_STATES,
    DEFAULT_WS_OPENING_TIMEOUT_MS,
    DEFAULT_PING_INTERVAL_MS
};
